### ISSUE TITLE
Not working inside raspberry pi using docker.

### ISSUE THREAD

**Issue by 3rg1s** [evilsocket/shieldwall#5] opened 2021-03-15 15:34 UTC
Hello there again.

Inside a raspberry pi I have a docker containers. I have exposed the port 8989 to point to port 80 inside the docker container. So everytime I hit my host ip on port 8989 the request gets forwarded to port 80 inside the container. Shieldwall was unable to block that request.

**Comment by evilsocket** [comment] 2021-03-16 18:13
hi! can you share the output of "sudo iptables -nL" ?

**Comment by 3rg1s** [comment] 2021-03-16 18:23
Note that when I write [TRUNCATED] there were like 5000 lines of the same thing there I do not know why.

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http-alt
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http-alt
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
[TRUNCATED]
SHIELDWALL  all  --  anywhere             anywhere
LOGNDROP   all  --  anywhere             anywhere

Chain FORWARD (policy DROP)
target     prot opt source               destination
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain DOCKER (3 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             1c1ab4c240c5         tcp dpt:http
ACCEPT     tcp  --  anywhere             1c1ab4c240c5         tcp dpt:https
ACCEPT     tcp  --  anywhere             1c1ab4c240c5         tcp dpt:domain
ACCEPT     udp  --  anywhere             1c1ab4c240c5         udp dpt:domain
ACCEPT     tcp  --  anywhere             172.17.0.3           tcp dpt:http

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (3 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain SHIELDWALL (1 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8989
ACCEPT     udp  --  anywhere             anywhere             udp dpt:8989
ACCEPT     tcp  --  localhost            anywhere             tcp dpts:tcpmux:65535
ACCEPT     udp  --  localhost            anywhere             udp dpts:1:65535

Chain LOGNDROP (1 references)
target     prot opt source               destination
LOG        all  --  anywhere             anywhere             limit: avg 10/min burst 5 LOG level warning prefix "shieldwall-dropped: "
DROP       all  --  anywhere             anywhere
```

**Comment by evilsocket** [comment] 2021-03-16 18:25
mmm do you have ufw running by any chance?

**Comment by 3rg1s** [comment] 2021-03-16 18:28
I did a mistake and had the allow rule on the logs I provided you. I had to put it on block or just leave the shieldwall without any logs at all. I just checked for ufw and I don't have it installed even inside the docker.

**Comment by evilsocket** [comment] 2021-03-16 18:30
i'm not sure i understand ... what rules you currently have configured? how does your config.yml look like? can you show me that output again after you restarted the shieldwall-agent service please? thanks

**Comment by 3rg1s** [comment] 2021-03-16 18:35
My iptables rules look like this:
```
hain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http-alt
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http-alt
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
SHIELDWALL  all  --  anywhere             anywhere
LOGNDROP   all  --  anywhere             anywhere

Chain FORWARD (policy DROP)
target     prot opt source               destination
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain DOCKER (3 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             1c1ab4c240c5         tcp dpt:http
ACCEPT     tcp  --  anywhere             1c1ab4c240c5         tcp dpt:https
ACCEPT     tcp  --  anywhere             1c1ab4c240c5         tcp dpt:domain
ACCEPT     udp  --  anywhere             1c1ab4c240c5         udp dpt:domain
ACCEPT     tcp  --  anywhere             172.17.0.3           tcp dpt:http

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (3 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain SHIELDWALL (1 references)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere
ACCEPT     tcp  --  localhost            anywhere             tcp dpts:tcpmux:65535
ACCEPT     udp  --  localhost            anywhere             udp dpts:1:65535

Chain LOGNDROP (1 references)
target     prot opt source               destination
LOG        all  --  anywhere             anywhere             limit: avg 10/min burst 5 LOG level warning prefix "shieldwall-dropped: "
DROP       all  --  anywhere             anywhere

```

My config.yml file :
```
# where to store the lists
data: '/var/lib/shieldwall/'
# path to iptables
iptables: '/sbin/iptables'
# check for newer versions and self update the agent
update: true

# api configuration
api:
  # api server to use
  server: 'https://shieldwall.me'
  # authentication token
  token: '[HIDDEN]'
  # api polling period in seconds
  period: 10
  # api timeout in seconds or 0 for no timeout
  timeout: 0

# list of ip addresses to always allow just in case
allow:
  - '127.0.0.1'

# log dropped packets to syslog
drops:
  log: true
  limit: '10/min'
  prefix: 'shieldwall-dropped'
  level: 4
```

**Comment by evilsocket** [comment] 2021-03-16 18:41
thanks, i'll try to reproduce it and then fix it asap

**Comment by 3rg1s** [comment] 2021-03-16 18:42
No worries. Note that I am using port forwarding from my isp router. And I am using a domain name to access that port since I don't know the ip.

**Comment by evilsocket** [comment] 2021-03-16 18:43
yep i figured! :D

**Comment by evilsocket** [comment] 2021-05-14 15:33
it should be fixed on latest

**Closed by evilsocket** 2021-05-14 15:33 UTC

**Comment by sadimusi** [comment] 2022-01-09 11:29
This does not appear to be working, as shieldwall is not part of the `FORWARD` chain at all. Because of the way shieldwall is set up (`ACCEPT`+`DROP` in two chains rather than `RETURN`+`DROP` in one), I was unable to properly integrate it there.

As a somewhat hacky workaround it's possible to add the two shieldwall chains to `DOCKER-USER`:
```
iptables -I DOCKER-USER -j LOGNDROP
iptables -I DOCKER-USER -j SHIELDWALL
iptables -I DOCKER-USER -i docker0 -j ACCEPT
```
This works fine for most use-cases, but it does not properly delegate to the `DOCKER` chain as it should. (See the [docker documentation](https://docs.docker.com/network/iptables/) on that topic.)
